spring.application.name=Bogle-Bogle

# Server Port
server.port=8080

# MySQL Connection Details
spring.datasource.url=jdbc:mysql://localhost:3306/bogle_bogle?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=yejin0913

# JPA / Hibernate SQL log settings
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# [중요] Workbench 데이터를 안전하게 유지하기 위해 ddl-auto는 validate(검증만 수행)로 설정합니다.
spring.jpa.hibernate.ddl-auto=validate